os: osx
osx_image: xcode9.3

stages:
  - build ios
  - build android

jobs:
  include:
    - stage: build ios
      language: node_js
      node_js:
        - 8.14.1
      env: app_ios=MobileApp.app_$TRAVIS_JOB_NUMBER.zip
      before_install:
       - echo -n "Starting " > info.txt
       - date >> info.txt
       - date
       - ls -l
      install:
        - npm install
        - ./scripts/travis_version.rb "src/version.js" "$TRAVIS_BUILD_NUMBER" "$TRAVIS_BRANCH"
        - cat src/version.js
        - cd ios
        - pod install
        - cd ..
      script:
        - |
          xcodebuild \
            -workspace ios/MobileApp.xcworkspace \
            -scheme MobileApp \
            -configuration Release \
            -sdk iphonesimulator \
            -derivedDataPath ios/build \
            -quiet
      after_success:
        - cd $var1
        - ls -lahtO
        - pwd
        - zip -qr $app_ios MobileApp.app
        - ls -lh *zip
        - cd $TRAVIS_BUILD_DIR
      after_script:
        - date
        - pwd
        - ls -lahtO
        - find ios/build/ -type d -maxdepth 5 | grep MobileApp.app
        - curl https://api.travis-ci.com/v3/job/$TRAVIS_BUILD_ID/log.txt -o travis-ci_output.txt
        - "echo \"branch: $TRAVIS_BRANCH\" >> info.txt"
        - "echo \"build dir: $TRAVIS_BUILD_DIR\" >> info.txt"
        - "echo \"commit: $TRAVIS_COMMIT\" >> info.txt"
        - "echo \"Variables:\" >> info"
        - set >> info.txt
        - "echo -n \"Ending \" >> info.txt"
        - date >> info.txt
        - date

    - stage: build android
      language: android
      jdk: oraclejdk8
      env: app_android=MobileApp_$TRAVIS_JOB_NUMBER_$TRAVIS_BRANCH.apk
      android:
        components:
          - build-tools-27.0.3
          - android-27
      before_install:
        - date
        - which java
        - java -version
        - ls -l
      install:
        - npm install
      script:
        - cd android
        - ./gradlew assembleRelease
      after_success:
        - zip -qr $app_ios $var1
        - ls -lh *zip
      after_script:
        - date
        - ls -lahtO
        - find android/app/outputs/apk/ -type f | grep apk
        - curl https://api.travis-ci.com/v3/job/$TRAVIS_BUILD_ID/log.txt -o travis-ci_output.txt
        - ls -lahtO
        - date
